#### SQL Joins lab ####

USE sakila;

# Write SQL queries to perform the following tasks using the Sakila database:
# 1. List the number of films per category.
SELECT COUNT(title), name
FROM film
INNER JOIN film_category
on film.film_id = film_category.film_id
INNER JOIN category
on film_category.category_id = category.category_id  
GROUP BY name;

# 2 .Retrieve the store ID, city, and country for each store.
SELECT store_id, city, country
FROM store
INNER JOIN address
on store.address_id = address.address_id
INNER JOIN city
on address.city_id = city.city_id
INNER JOIN country
on city.country_id = country.country_id;

# 3. Calculate the total revenue generated by each store in dollars.
SELECT store_id, amount as revenue
FROM store
INNER JOIN staff
on store.store_id = staff.store_id
INNER JOIN payment
on staff.staff_id = payment.staff_id;


# 4. Determine the average running time of films for each category.
SELECT avg(length), name
FROM film
INNER JOIN film_category
on film.film_id = film_category.film_id
INNER JOIN category
on film_category.category_id = category.category_id  
GROUP BY name;

# Bonus:
# 5. Identify the film categories with the longest average running time.
SELECT avg(length) as avg_length, name
FROM film
INNER JOIN film_category
on film.film_id = film_category.film_id
INNER JOIN category
on film_category.category_id = category.category_id  
GROUP BY name
ORDER BY avg_length DESC
LIMIT 1;

# 6. Display the top 10 most frequently rented movies in descending order.
SELECT rental_date, title
FROM rental
INNER JOIN inventory
ON rental.inventory_id = inventory.inventory_id  
INNER JOIN film
ON inventory.film_id = film.film_id 
ORDER BY rental_date DESC
LIMIT 10;

# 7. Determine if "Academy Dinosaur" can be rented from Store 1.


# 8. Provide a list of all distinct film titles, along with their availability status in the inventory. 
# Include a column indicating whether each title is 'Available' or 'NOT available.' 
# Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."